version: "3"

services:
  zxinfo-vue:
    build:
      context: ../zxinfo-vue
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8200:80"
    expose:
      - "8200"
    environment:
      NODE_ENV: production

